# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'iCasting' do
pod 'Google/CloudMessaging'
end

target 'iCastingTests' do
pod 'Google/CloudMessaging'
end

